name: workflow-practice
on:
  issues:
    types: [opened,edited,deleted]
jobs:
  job2:
    runs-on: ubuntu-latest
    steps: 
      - name: Checking out in repository
        uses: actions/checkout@v3
      - name: Printing hello
        run: |
          echo "Hello Sheetal"

