name: workflow-practice
on:
  issues:
    types: [opened,edited,deleted]
jobs:
  job2:
    runs-on: ubuntu-latest
    steps: 
      - name: Checking out in repository
        uses: actions/checkout@v3
      - name: Printing hello
        run: |
          echo "Hello Sheetal"

---
name: workflow-practice-1
on: [push]
jobs:
  job1:
      runs-on: ubuntu-latest
      steps:
        - name: Checking out in git repository
          uses: actions/checkout@v3
        - name: Installing dependencies
          run: npm ci
        - name: Linting
          run: npm run lint
        - name: Testing scripts
          run: npm run test