name: workflow-practice
on:
  issues:
    types: [opened,edited,deleted]
jobs:
  job2:
    runs-on: ubuntu-latest
    steps: 
      - name: Checking out in repository
        uses: actions/checkout@v3
      - name: Printing hello
        run: |
          echo "Hello Sheetal"
      - name: printing github context
        run: |
          touch file.json
          echo "${{ toJSON(github) }}" >> file.json
          cat file.json
      - name: saving github fil in artifact
        uses: actions/upload-artifact@v3
        with: 
          name: github-artifacts-file
          path: file.json
      - name: Download a single artifact
        uses: actions/download-artifact@v3
        with:
          name: github-artifact-file
